---
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
mode: rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7894
  fallback-filter:
  geoip: true
  geoip-code: ID
  ipcidr:
  - 0.0.0.0/8
  - 10.0.0.0/8
  - 100.64.0.0/10
  - 127.0.0.0/8
  - 169.254.0.0/16
  - 172.16.0.0/12
  - 192.0.0.0/24
  - 192.0.2.0/24
  - 192.88.99.0/24
  - 192.168.0.0/16
  - 198.18.0.0/15
  - 198.51.100.0/24
  - 203.0.113.0/24
  - 224.0.0.0/4
  - 240.0.0.0/4
  - 255.255.255.255/32
  domain:
  - "+.google.com"
  - "+.facebook.com"
  - "+.youtube.com"
  - "+.githubusercontent.com"
  - "+.googlevideo.com"
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  fake-ip-filter:
  - "+.pool.ntp.org"
  - ntp7.*.com
  - ntp6.*.com
  - ntp5.*.com
  - ntp4.*.com
  - ntp3.*.com
  - ntp2.*.com
  - ntp1.*.com
  - ntp.*.com
  - time7.*.com
  - time6.*.com
  - time5.*.com
  - time4.*.com
  - time3.*.com
  - time2.*.com
  - time1.*.com
  - time.*.apple.com
  - time.*.edu.cn
  - time.*.gov
  - time.*.com
  - "*.home.arpa"
  - "*.local"
  - "*.test"
  - "*.localhost"
  - "*.invalid"
  - "*.example"
  - "*.localdomain"
  - "+.stun.*.*.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*"
  - stun.*.*.*
  - stun.*.*
  - time1.cloud.tencent.com
  - "*.ntp.org.cn"
  - "*.time.edu.cn"
  - "*.lan"
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - https://dns.google/dns-query
  - tls://dns.google
proxy-providers:
  master-isp:
    type: file
    path: "./master-isp.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
proxy-groups:
- name: SIMASTER-V1.3
  type: select
  disable-udp: false
  proxies:
  - LOADBALANCE
  - RELAY
  - MANUAL
  - AUTO
  - FAILOVER
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: PORT-UMUM
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - DIRECT
  - SIMASTER-V1.3
- name: PORT-MOBILELEGENDS
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - SIMASTER-V1.3
- name: PORT-GARENA
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - SIMASTER-V1.3
- name: PORT-PUBG
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - SIMASTER-V1.3
- name: PORT-CALLOFDUTY
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - SIMASTER-V1.3
- name: LOADBALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - master-isp
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: MANUAL
  type: select
  disable-udp: false
  use:
  - master-isp
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: AUTO
  type: url-test
  disable-udp: false
  use:
  - master-isp
  url: http://www.gstatic.com/generate_204
  interval: '99'
  tolerance: '99'
- name: FAILOVER
  type: fallback
  disable-udp: false
  use:
  - master-isp
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: RELAY
  type: relay
  disable-udp: false
  use:
  - master-isp
- name: WHATSAPP
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - SIMASTER-V1.3
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: SOSMED
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - SIMASTER-V1.3
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: STREAM
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - SIMASTER-V1.3
- name: GAME
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - SIMASTER-V1.3
- name: AMANKAN-ANAK
  type: select
  disable-udp: false
  proxies:
  - REJECT
rule-providers:
  Koneksi-Proxy:
    type: file
    behavior: classical
    path: "./koneksi-proxy.yaml"
  Bypass-Whatsapp:
    type: file
    behavior: domain
    path: "./bypass-whatsapp.yaml"
  Bypass-Sosmed:
    type: file
    behavior: classical
    path: "./bypass-sosmed.yaml"
  Bypass-Stream:
    type: file
    behavior: classical
    path: "./bypass-stream.yaml"
  Bypass-Game:
    type: file
    behavior: classical
    path: "./bypass-game.yaml"
  Safety-Child:
    type: file
    behavior: classical
    path: "./safety-child.yaml"

rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DST-PORT,989,AMANKAN-ANAK
- DST-PORT,10087,AMANKAN-ANAK
- IP-CIDR,198.18.0.1/16,AMANKAN-ANAK,no-resolve
- RULE-SET,Koneksi-Proxy,SIMASTER-V1.3
- RULE-SET,Bypass-Whatsapp,WHATSAPP
- RULE-SET,Bypass-Sosmed,SOSMED
- RULE-SET,Bypass-Stream,STREAM
- RULE-SET,Bypass-Game,GAME
- RULE-SET,Safety-Child,AMANKAN-ANAK
- GEOIP,ID,SIMASTER-V1.3
- MATCH,SIMASTER-V1.3
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
bind-address: "*"
